### ISSUE TITLE
Exception while building the HTML doc

### ISSUE THREAD

**Issue by multani** [zatosource/zato-docs#10]
Attempting to build the HTML doc results in the following error:

```
# Sphinx version: 1.2.2
# Python version: 2.7.7rc1
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
#   djangodocs from /home/jon/projects/externs/zato/zato-docs/sphinx/_ext/djangodocs.py
#   sphinx.ext.oldcmarkup from /home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/sphinx/ext/oldcmarkup.pyc
Traceback (most recent call last):
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 276, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 320, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 333, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 433, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/sphinx/writers/html.py", line 51, in translate
    self.document.walkabout(visitor)
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/home/jon/projects/externs/zato/env-2.7/local/lib/python2.7/site-packages/docutils/writers/html4css1/__init__.py", line 1559, in depart_table
    self.compact_p = self.context.pop()
IndexError: pop from empty list
```

Note that the packages installed used to build the doc are from a brand new virtualenv, in which I did `pip install sphinx`, but I get the same result if I use the packages provided by my Linux distribution (Debian Sid, up-to-date at the moment)

**Comment by dsuch** [comment]
For future reference - checking out the documentation from GH and running ..

```
$ make virtualenv
$ make html
```

.. will build HTML docs under virtualenv using dependencies in exact versions that are known to work.

Thanks everyone, I'll be closing the ticket.
