### ISSUE TITLE
Random error about redis

### ISSUE THREAD

**Issue by MikHulk** [zatosource/zato-docs#44]
Helllo,

I run zato in a docker I built with instruction given in the documentaiton (https://zato.io/docs/admin/guide/install/docker.html).

I am on the second part of the tutorial.

The redis connection works:

```
zato@07ad870f8dd3:~$ zato check-config env/qs-1/server1
SQL ODB connection OK
Redis connection OK
zato@07ad870f8dd3:~$ zato check-config env/qs-1/server2
SQL ODB connection OK
Redis connection OK
zato@07ad870f8dd3:~$
```

but I get sometimes an error about redis:
```
2019-03-30 13:29:35,454 DEBG 'zato-server2' stdout output:
2019-03-30 13:29:35,454 - WARNING - 637:DummyThread-64 - zato.server.service:502 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 494, in update_handle
    service.post_handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 730, in post_handle
    self.kvdb.conn.hmset(key, data)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/redis/client.py", line 2011, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/redis/connection.py", line 636, in read_response
    raise response
ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value


2019-03-30 13:29:35,456 DEBG 'zato-server2' stdout output:
2019-03-30 13:29:35,455 - ERROR - 637:DummyThread-64 - zato.server.connection.http_soap.channel:324 - Caught an exception, cid:`889456f224c99b42a964013e`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 268, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 502, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 494, in update_handle
    service.post_handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 730, in post_handle
    self.kvdb.conn.hmset(key, data)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/redis/client.py", line 2011, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/redis/connection.py", line 636, in read_response
    raise response
ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value

```

I don't know from where this error occur (Zato, Redis, or the docker). 

Do you have an idea of what this error is due to ?

Regards,

**Comment by dsuch** [comment]
Hello,

I have not seen it before and while I do understand the error message, I am not sure why it could happen.

Please try to find out how to reproduce it and then I will be able to investigate it.

By the way, for non-documentation related tickets, please open them in [zatosource/zato](https://github.com/zatosource/zato).

Thank you.

**Comment by MikHulk** [comment]
Hello,

Oh, sorry for the wrong place for this ticket.

I have restart the docker and I don't have the error anymore. I will try to reproduce as soon as will finish the tutorial.

Thx

**Comment by dsuch** [comment]
Sure, this is all good - it is just that opening non-docs tickets in zatosource/zato lets us reference tickets numbers in commits, e.g. ticket #44 here is not the same as #44 over there.

**Comment by dsuch** [comment]
Mass-closing old tickets.
