### ISSUE TITLE
AttributeError on 'Simple' object on tutorial 2d part

### ISSUE THREAD

**Issue by MikHulk** [zatosource/zato-docs#46]
Hello,

the code from tutorial here: https://zato.io/docs/tutorial/02.html#sending-messages-asynchronously

raise this error:
```
2019-03-30 16:51:51,866 DEBG 'zato-server2' stdout output:
2019-03-30 16:51:51,866 - ERROR - 277:DummyThread-58 - zato.server.connection.http_soap.channel:324 - Caught an exception, cid:`36d283c39aab2d1cb68b7719`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 268, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 502, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/server2/work/hot-deploy/current/client_details.py", line 50, in handle
    self.outgoing.zmq.send(fraud_request, 'Fraud detection')
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/zmq_/outgoing.py", line 45, in send
    conn.send(msg, *args, **kwargs)
  File "/opt/zato/3.0/code/zato-zmq/src/zato/zmq_/outgoing.py", line 24, in send
    self.impl.send_string(msg)
AttributeError: 'Simple' object has no attribute 'impl'
```

this is how the outgoing connection is configured in my setup:
![capt](https://user-images.githubusercontent.com/10364941/55279116-1566fb80-5315-11e9-9639-8553249e9eae.png)
 

This is the service as it is configured in zato:

```python
# stdlib
from datetime import datetime
from json import dumps

# Zato
from zato.server.service import Service

class GetClientDetails(Service):

    def should_notify_frauds(self, cust_type):
        config_key = 'myapp:fraud-detection:cust-type'
        return cust_type in ('A', 'B', 'C')

    def handle(self):

        self.logger.info('Request: {}'.format(self.request.payload))
        self.logger.info('Request type: {}'.format(type(self.request.payload)))

        # Fetch connection to CRM
        crm = self.outgoing.plain_http.get('CRM')

        # Fetch connection to Payments
        payments = self.outgoing.plain_http.get('Payments')

        # Grab the customer info ..
        response = crm.conn.send(self.cid, self.request.payload)
        cust = response.data

        # .. and last payment's details
        response = payments.conn.send(self.cid, self.request.payload)
        last_payment = response.data

        self.logger.info('Customer details: {}'.format(cust))
        self.logger.info('Last payment: {}'.format(last_payment))

        response = {}
        response['first_name'] = cust['firstName']
        response['last_name'] = cust['lastName']
        response['last_payment_date'] = last_payment['DATE']
        response['last_payment_amount'] = last_payment['AMOUNT']

        if self.should_notify_frauds(self.request.payload['cust_type']):

            fraud_request = {}
            fraud_request['timestamp'] = datetime.utcnow().isoformat()
            fraud_request['request'] = dumps(self.request.payload)
            fraud_request['response'] = response
            fraud_request = dumps(fraud_request)

            self.outgoing.zmq.send(fraud_request, 'Fraud detection')

        else:
            self.logger.info('Skipped fraud detection for CID {}'.format(self.cid))

        self.logger.info('Response: {}'.format(response))

        # And return response to the caller
        self.response.payload = response
```

What is the problem ?

Regards,

**Comment by dsuch** [comment]
Since this is about an exception in code - can you please reopen the ticket in the other repository?

**Comment by MikHulk** [comment]
Yes I am gonna do this straight away

**Comment by MikHulk** [comment]
I have created the ticket https://github.com/zatosource/zato/issues/934 thx !
